### ISSUE TITLE
Exception when custom password is set

### ISSUE THREAD

**Issue by matmorillon** [blacklabelops/hsqldb#1]
When you specify a password with a not null nor empty value (using environment variable HSQLDB_PASSWORD) and try to connect to your hsqldb instance, you'll get following error :

```
org.hsqldb.HsqlException: invalid authorization specification
    at org.hsqldb.error.Error.error(Unknown Source)
    at org.hsqldb.error.Error.error(Unknown Source)
    at org.hsqldb.rights.User.checkPassword(Unknown Source)
    at org.hsqldb.rights.UserManager.getUser(Unknown Source)
    at org.hsqldb.Database.connect(Unknown Source)
    at org.hsqldb.DatabaseManager.newSession(Unknown Source)
    at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
    at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
    at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
```

I don't get this error when no password is set.
I take a look in the entrypoint shell script and find a typo i guess, let's see :

```
if [ -n "${HSQLDB_USER}" ]; then
  hsqldb_user=${HSQLDB_USER}
fi
​
hsqldb_password=""
​
if [ -n "${HSQLDB_PASSWORD}" ]; then
  hsqldb_user=${HSQLDB_PASSWORD}
fi
```

Fix easy

**Comment by matmorillon** [comment]
Thank you for you quick fix
